name: Keep Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:  # allows manual trigger for testing

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server with retries
        run: |
          curl -A "Mozilla/5.0" \
               --retry 10 \
               --retry-delay 6 \
               --retry-max-time 70 \
               --max-time 65 \
               --connect-timeout 10 \
               https://moonai-backend.onrender.com/ \
            || echo "Server is still waking up, but we're keeping it warm."
