name: Keep Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:  # optional, allows manual runs

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping to Keep Alive
        run: |
          # Wait up to 70 seconds (includes retries)
          curl -A "Mozilla/5.0" \
               --retry 2 \
               --retry-delay 10 \
               --retry-max-time 70 \
               --max-time 60 \
               https://moonai-backend.onrender.com/ \
            || echo "Server did not respond in time, likely still waking up."
