name: Keep Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping to Keep Alive
        run: |
          curl -m 10 --retry 5 https://moonai-backend.onrender.com/
