name: Keep Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:  # allows manual trigger for testing

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping both Render servers with retries
        run: |
          echo "Pinging moonai-api..."
          curl -A "Mozilla/5.0" \
               --retry 10 \
               --retry-delay 6 \
               --retry-max-time 70 \
               --max-time 65 \
               --connect-timeout 10 \
               https://moonai-api.onrender.com/ \
            || echo "moonai-api is still waking up, but we're keeping it warm."

          echo "Pinging moonai-backend..."
          curl -A "Mozilla/5.0" \
               --retry 10 \
               --retry-delay 6 \
               --retry-max-time 70 \
               --max-time 65 \
               --connect-timeout 10 \
               https://moonai-backend.onrender.com/ \
            || echo "moonai-backend is still waking up, but we're keeping it warm."
